server:
  port: 8000
  servlet:
    context-path: /users

spring:
  application:
    name: user-svc

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

google:
  secret-manager:
    project-id: 697886067979
    secret-id: user-svc
    version: latest

environment: DEV
